### ISSUE TITLE
Subscribe error ,please help

### ISSUE THREAD

**Issue by ckcsb** [michaelfig/mediasoup-broadcast-example#1]
When click subscribe,there is a error  alert, Cannot subscribe to channel: SyntaxError: Failed to construct 'RTCPeerConnection': '' is not a valid URL.

**Comment by michaelfig** [comment]
Can you please specify your browser, and the (anonymized, if necessary) subscriber page URL?

**Comment by jaydgoss** [comment]
Seeing this is well on both broadcaster and subscriber side.
Testing on Chrome 70.0.3538.77

**Comment by ckcsb** [comment]
I start this project use  PORT=8080 node server/index.js ，It seems to run ok，I use  http://172.16.70.213:8080/publish.html  to publish，and I use http://172.16.70.213:8080/  to Subscribe，but when click Publish，alert this error like this
use Chrome（67.0.3396.62），error message is ：
Cannot subscribe to channel: SyntaxError: Failed to construct 'RTCPeerConnection': '' is not a valid URL.

use FireFox（63.0.1 ），error message is：
Cannot subscribe to channel: SyntaxError: RTCPeerConnection constructor passed invalid RTCConfiguration - malformed URI:

**Comment by michaelfig** [comment]
I've just released v1.1.1, which fixes this issue.

Thanks for the report,
Michael.
