### ISSUE TITLE
Error getting media (error code 0) under iPad for publishing

### ISSUE THREAD

**Issue by lakano** [michaelfig/mediasoup-broadcast-example#2]
hello!

Thanks for your works.
On an iPad Safari ( latest iOS, v12.1.1 ), I can play correctly a stream, but I can't publish anything from the iPad. 

I've tried to enable/disable camera/audio, nothing works. 
I've also tried to inject webrtc-adapter but this doesn't help.

Regards,

**Comment by michaelfig** [comment]
Hi,

Can you go to:

https://webrtc.github.io/samples/src/content/getusermedia/gum/

And does that work for you?

If not, this is a deeper problem than just the mediasoup-broadcast-example.

Hope this helps,
Michael.

**Comment by lakano** [comment]
@michaelfig Thanks for the quick answer :)
The Gum sample works correctly from my iPad.
Tell me if I can do more tests/debug.
Regards,

**Comment by michaelfig** [comment]
Are you serving the broadcast example over https?

**Comment by lakano** [comment]
not yet, I'm under « localhost », do you think on iOS, we can't share mic/video even on localhost ?

**Comment by michaelfig** [comment]
How are you running the broadcast example node.js server on iOS?  I think
that's not possible... Localhost can only be served on macos or Linux.

**Comment by lakano** [comment]
On my network, I have multiple linux/windows/macos machines. The server run under a linux host.
I'll try to add a TLS cert to check if this works. I surely need to do a nginx reverse proxy with a self-signed cert.

**Comment by michaelfig** [comment]
Yes, that would be the problem.

When I say "localhost", I mean literally 127.0.0.1.  iOS cannot use a
non-localhost address with getUserMedia unless it is with HTTPS.

Also make sure the certificate is trusted by iOS, too.

Good luck!
Michael.

**Comment by lakano** [comment]
Ok thanks for the precisions! 
And Happy New Year :)

**Comment by lakano** [comment]
I confirm, this was exactly the problem! Thanks :)

**Comment by michaelfig** [comment]
Great!  Happy new year!
