### ISSUE TITLE
broadcast avi video

### ISSUE THREAD

**Issue by nodejscss** [michaelfig/mediasoup-broadcast-example#4]
Hi, MichaelFig,

I just ran the example, and it ran well.

It also can broadcast the big_buck_bunny.mp4 video. I copy a avi file, test.avi, to the app/videos/ directory , and change the Video SRC from big_buck_bunny.mp4 to test.avi. But It can not broadcast the avi stream.

Would you please tell me how to broadcast the avi video like mp4 video ?

Thank you very much.

**Comment by michaelfig** [comment]
Hi,

Can your web browser that you're using for the publisher play the video directly, without mediasoup-broadcast-example?  That is:

1. put the `test.avi` on your local workstation
2. do `File -> Open File...` in your web browser and choose the saved `test.avi` file

If the browser doesn't play the video there, it's a different issue.

Let me know what you find out.

Hope this helps,
Michael.

**Comment by nodejscss** [comment]
Hi, Michael,

Yes. You are right. Following the above steps, the browses doesn't play the avi video.

I convert avi to H264 by doing command:

HandBrakeCLI -i test.avi -o test.mp4 -e x264

then it can broadcast the test.mp4 video.

There are an additional job to convert avi to H264 and it takes much more time to do conversion job.

Thank you for your help.

**Comment by michaelfig** [comment]
Glad you found a solution!

Closing this ticket,
Michael.
