### ISSUE TITLE
How to run this service on a server with a publicly accessible IP address

### ISSUE THREAD

**Issue by 205721860** [michaelfig/mediasoup-broadcast-example#9]
Hi
Michael

I want run this service on a server with a publicly accessible IP address
Now,I have  a problem.
The specific steps are as follows
**Step 1**
`HTTPS_HOST=0.0.0.0 PORT=443 node server/index.js`
**return**
`Listening for HTTPS on 0.0.0.0:443`
**Step 2**
Enter in browser `https://starcloud.work/publish.html`  Selection  `Publish` Click `Capture` 
**return**
```
xx.xx.xxx.xx 33546 Authorizing publisher to test
xx.xx.xxx.xx 33546 new peer joined the room publisher
```
**Step 3**
Enter in browser `https://starcloud.work/` Selection  `Subscribe`
**return**
```
xx.xx.xxx.xx 33618 Authorizing subscriber to test
xx.xx.xxx.xx 33618 new peer joined the room 0.8056946895632191

```
There was an error in **Step 3**  Can not see publisher

Thanks
Xiu Feng

**Comment by michaelfig** [comment]
Hi, have you read the part of the readme that describes `RTC_ANNOUNCED_IPV4` ?

It seems like it could be a firewall/networking issue, especially if it works for you on localhost.

**Comment by michaelfig** [comment]
Also, look at the browser console log for more clues.

**Comment by 205721860** [comment]
in Step 2. Enter in browser `https://starcloud.work/publish.html` Selection `Publish` Click `Capture`

Video & Audio show speed **0KB/s**

How to resolve the problem

**Comment by michaelfig** [comment]
This may be the same issue as #8.  Try instead of capturing the movie to set to "Camera" and "Microphone" before clicking "Capture".
